export { default as Breadcrumb } from '@/components/Breadcrumb/index.vue'
export { default as HeaderBar } from './Header/index.vue'
export { default as Sidebar } from './Sidebar/index.vue'
export { default as RightPanel } from './right-panel/index.vue'
export { default as TagsView } from './tags-view/index.vue'
export { default as Breadcrumbs } from './breadcrumbs/index.vue'
export { default as Setting } from './setting/index.vue'
